# List of elvm Backends to build and test
#
# @param $FULL iff 1, a full test will be performend in addition to a simple
#     build
# @param $SELFHOST iff 1, a self hosting test will be performed in addition to
#     a simple build
#
# Some targets will not perform a full test or self hosting test even if they
# don't fail since those tests might exceed Travis CI's time limit
env:
  matrix:
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=0 TARGET='asmjs'
    - TEST=1 TEST_FULL=0 TEST_SELFHOST=0 TARGET='bef'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=0 TARGET='bf'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=0 TARGET='c'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=0 TARGET='cl'
    - TEST=0 TEST_FULL=0 TEST_SELFHOST=0 TARGET='cmake'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=0 TARGET='cpp'
    - TEST=0 TEST_FULL=0 TEST_SELFHOST=0 TARGET='cr'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=0 TARGET='cs'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=1 TARGET='el'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=1 TARGET='forth'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=1 TARGET='fs'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=1 TARGET='go'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=1 TARGET='hs'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=1 TARGET='i'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=1 TARGET='java'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=1 TARGET='js'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=1 TARGET='ll'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=1 TARGET='lua'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=1 TARGET='oct'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=1 TARGET='php'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=1 TARGET='pl'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=0 TARGET='ps'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=0 TARGET='py'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=0 TARGET='rb'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=0 TARGET='rs'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=0 TARGET='scala'
    - TEST=1 TEST_FULL=1 TEST_SELFHOST=1 TARGET='x86'


# Build target and execute as many tests as possible, restricted by Travis CI
# runtime limit
script:
  - mc $TARGET make build-$TARGET
  - if [ $TEST == '1' ]; then mc $TARGET make test-$TARGET; fi
  - if [ $TEST_FULL == '1' ]; then mc $TARGET make test-$TARGET-full; fi
  - if [ $TEST_SELFHOST == '1' ]; then mc $TARGET ./tools/check_selfhost.sh $TARGET; fi


# Install target specific environment in Docker container
install:
 - npm install -g mini-cross
 - mc $TARGET echo $TARGET

language: node_js

services:
 - docker

